### ISSUE TITLE
There's a permission denied message I can't configure

### ISSUE THREAD

**Issue by mehrnazayazi** [QingdaoU/OnlineJudge#168]
We've been trying to request to judge server that we have on docker and is up we send the following HTTP request body(we have already pinged the server and every thing was ok):
```

{
   "language_config": {
       "template": "",
        "compile": {
            "src_name": "main.cpp",
            "exe_name": "compiler.out",
            "max_cpu_time": 3000,
            "max_real_time": 10000,
            "max_memory": 51200000,
            "compile_command": "/usr/bin/g++ -DONLINE_JUDGE -O2 -w -fmax-errors=3 -std=c++14 {src_path} -lm -o {exe_path}"
        },
        "run": {
            "command": "{exe_path}",
            "seccomp_rule": "c_cpp",
            "env": "default_env"
        }
    },
   "src": "int main() { return 0;}",
   "max_cpu_time": 300,
   "max_memory": 51200000,
   "test_case_id": "normal"
}
```

we couldn't find anything that could help in the document.
we traced the code to Judger unit and we realized we get the error from there.
response that we catch is as bellow:
```
{
    "err": "CompileError",
    "data": "/usr/bin/ld: cannot open output file /judger/run/0edaae0eca53482c859d58df9f24161e/compiler.out: Permission denied\ncollect2: error: ld returned 1 exit status"
} 
```

minor changes were applied to docker-compose file so I will attach the changed file too

```
version: "3"
services:
    judge_server:
        build: .
        read_only: true
        cap_drop:
            - SETPCAP
            - MKNOD
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
            - FSETID
        tmpfs:
            - /tmp
        volumes:
            - ./tests/test_case:/test_case:ro
            - ./log:/log
            # - $PWD/log:/log
            # - $PWD/server:/code:ro
            - ./run:/judger
        environment:
            - BACKEND_URL=http://127.0.0.1:8000/api/judge_server_heartbeat
            - SERVICE_URL=http://127.0.0.1:12358
            - TOKEN=03AC674216F3E15C761EE1A5E255F067953623C8B388B4459E13F978D7C846F4
            - judger_debug=1
        ports:
            - "0.0.0.0:12358:8080"
```
