### ISSUE TITLE
示例代码（A + B Problem）java代码提交总是出现runtime error，C代码提交没有问题

### ISSUE THREAD

**Issue by ganting** [QingdaoU/OnlineJudge#23]
抱歉，我这边上传图片有问题。

我本地按照文档一步步安装了web和backend，所有的都没有问题，就是我新建一个A + B Problem的测

试题目后，用c提交可以Accepted，但是用java始终报RuntimeError。

请问这个会是什么问题？谢谢！

下面是我的判题后台的compose文件 : 
```yml
judger:                        
       image: duoj/judger
       volumes:                   
           - /root/haeoj/OnlineJudge:/var/judger/code
           - /root/haeoj/test_case:/var/judger/test_case
           - /root/haeoj/log:/var/judger/code/judge/log
       environment:               
           - rpc_token=123456     
       ports:                     
           - "127.0.0.1:8085:8080" 
```
