### ISSUE TITLE
Setup Help!!!

### ISSUE THREAD

**Issue by narendraomprakash** [QingdaoU/OnlineJudge#313]
Setup instructions need to be clear. I have no clue on how to run the judge, + register button is not shown in the home page+how can I access admin interface ? Please help me.

**Comment by renbaoshuo** [comment]
Use [qduoj.com](https://qduoj.com) as an example:

+ The registration button is displayed in the upper left corner of the page.

![image.png](https://i.loli.net/2020/08/15/G29gltM1wiZPzOQ.png)

+ The admin interface is available in `/admin` URL (example: <https://qduoj.com/admin>)

**Comment by narendraomprakash** [comment]
Can you help me setup the website? If you don’t mind, in case you are ok with it I’ll share with you my whatsapp number or any comfortable medium of conversation

**Comment by renbaoshuo** [comment]
https://github.com/QingdaoU/OnlineJudgeDeploy   <~ You can see the setting method here.

**Comment by renbaoshuo** [comment]
## Environmental preparation (Linux)

+ System: Ubuntu 18.04 LTS

1. Install the necessary dependencies

    ```bash
    sudo apt-get update
    sudo apt-get install -y vim python-pip curl git
    pip install docker-compose
    ```

2. Install Docker

    Install using script: `sudo curl -sSL get.docker.com | sh`

    Other installation methods: [https://docs.docker.com/install/](https://docs.docker.com/install/)

## Install

1. Please select a location with some surplus disk space and run the following command:

    ```bash
    git clone -b 2.0 https://github.com/QingdaoU/OnlineJudgeDeploy.git && cd OnlineJudgeDeploy
    ```

2. Start service

    ```bash
    docker-compose up -d
    ```

According to the network speed, the setup can be completed automatically in about 5 to 30 minutes without manual intervention.

Wait for the command execution to complete, and then run `docker ps -a`. When you see that the status of all the containers does not have `unhealthy` or `Exited (x) xxx`, it means OnlineJudge has started successfully.

Access the server's HTTP 80 port or HTTPS 443 port through a browser, and you can start using it. The background management path is `/admin`, the super administrator user name automatically added during the installation process is `root`, and the password is `rootroot`. **If you log in successfully, please change your account password immediately.**.

Don't forget to read the documentation: http://docs.onlinejudge.me/

**Comment by renbaoshuo** [comment]
> Can you help me setup the website? If you don’t mind, in case you are ok with it I’ll share with you my whatsapp number or any comfortable medium of conversation

I'm a Chinese, so I don't have whatsapp account.

**Comment by narendraomprakash** [comment]
What about slack or something ? All of these are mentioned in the website/GitHUb itself. I reached out to you, because I failed miserably in these steps

**Comment by renbaoshuo** [comment]
Can you tell me the error message?

**Comment by narendraomprakash** [comment]
As such there is no error. I am clueless on how to proceed further for judgement

**Comment by renbaoshuo** [comment]
Can you send me the content displayed on the screen after running the command?

**Comment by ospiper** [comment]
Could you please provide some screenshots of the procedure of your deployment? Thus we can know more about your situation.

**Comment by narendraomprakash** [comment]
Yes I will get back to this after a couple of minutes. Got my exams tmw. Thank you for the response

**Comment by narendraomprakash** [comment]
ERROR: for oj-backend  Cannot start service oj-backend: Ports are not available: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for oj-backend  Cannot start service oj-backend: Ports are not available: listen tcp 0.0.0.0:80: bind: address already in use

I get this error when I execute docker-compose up -d

CONTAINER ID        IMAGE                                                        COMMAND                  CREATED             STATUS                      PORTS               NAMES
5602bf8f5157        registry.cn-hangzhou.aliyuncs.com/onlinejudge/oj_backend     "/bin/sh -c /app/dep…"   49 minutes ago      Created                                         oj-backend
45a1b281501b        postgres:10-alpine                                           "docker-entrypoint.s…"   49 minutes ago      Up 49 minutes               5432/tcp            oj-postgres
ce5d73e793b6        registry.cn-hangzhou.aliyuncs.com/onlinejudge/judge_server   "/bin/sh -c /code/en…"   49 minutes ago      Up 49 minutes (unhealthy)   8080/tcp            judge-server
458da05653f8        redis:4.0-alpine                                             "docker-entrypoint.s…"   49 minutes ago      Up 49 minutes               6379/tcp            oj-redis


thIS is the output of docker ps -a

**Comment by narendraomprakash** [comment]
I managed to deploy the entire website on the localhost
How do I customize the FE and then deploy it onto custom domain?

**Comment by renbaoshuo** [comment]
It seems that port 80 of your server is occupied. 

You can use the following to replace `docker-compose.yml`.

```yaml
version: "3"
services:

  oj-redis:
    image: redis:4.0-alpine
    container_name: oj-redis
    restart: always
    volumes:
      - ./data/redis:/data
  
  oj-postgres:
    image: postgres:10-alpine
    container_name: oj-postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge

  judge-server:
    image: registry.cn-hangzhou.aliyuncs.com/onlinejudge/judge_server
    container_name: judge-server
    restart: always
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/log:/log
      - ./data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://judge-server:8080
      - BACKEND_URL=http://oj-backend:8000/api/judge_server_heartbeat/
      - TOKEN=CHANGE_THIS
      # - judger_debug=1
  
  oj-backend:
    image: registry.cn-hangzhou.aliyuncs.com/onlinejudge/oj_backend
    container_name: oj-backend
    restart: always
    depends_on:
      - oj-redis
      - oj-postgres
      - judge-server
    volumes:
      - ./data/backend:/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
      - JUDGE_SERVER_TOKEN=CHANGE_THIS
      # - FORCE_HTTPS=1
      # - STATIC_CDN_HOST=cdn.oj.com
    ports:
      - "0.0.0.0:10180:8000"
      - "0.0.0.0:10443:1443"
```

You can use a reverse proxy to realize the function of binding domain names, because the default is to directly listen to all requests on port 80.
