### ISSUE TITLE
docker部署出问题

### ISSUE THREAD

**Issue by LiuTianyouOnLuogu** [QingdaoU/OnlineJudge#322]
```
Recreating a81ded2b4c55_oj-backend ... error

ERROR: for a81ded2b4c55_oj-backend  Cannot start service oj-backend: driver failed programming external connectivity on endpoint oj-backend (c0993d4500347388c5378cdd00eb12edcf95e2652daaf00630cbad8f9857d889): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for oj-backend  Cannot start service oj-backend: driver failed programming external connectivity on endpoint oj-backend (c0993d4500347388c5378cdd00eb12edcf95e2652daaf00630cbad8f9857d889): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```
这咋整，容器端口绑定冲突了……

**Comment by renbaoshuo** [comment]
修改 docker-compose.yml 修改端口即可。

**Comment by LiuTianyouOnLuogu** [comment]
直接改？

**Comment by LiuTianyouOnLuogu** [comment]
搞成这样了：`- "80:84"`

**Comment by LiuTianyouOnLuogu** [comment]
要改80吗？我试试

**Comment by LiuTianyouOnLuogu** [comment]
貌似映射不上……这怎么办，我可以分配IP吗

**Comment by renbaoshuo** [comment]
```yaml
ports:
      - "0.0.0.0:10080:8000"
      - "0.0.0.0:10443:1443"
```

**Comment by LiuTianyouOnLuogu** [comment]
10080是什么端口

**Comment by renbaoshuo** [comment]
请参考文档。

**Comment by LiuTianyouOnLuogu** [comment]
这个部署之后就能直接用了？我为什么显示“无法访问此页面”？
```
version: "2"
services:

  oj-redis:
    image: redis:4.0-alpine
    container_name: oj-redis
    restart: always
    volumes:
      - ./data/redis:/data
  
  oj-postgres:
    image: postgres:10-alpine
    container_name: oj-postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge

  judge-server:
    image: registry.cn-hangzhou.aliyuncs.com/onlinejudge/judge_server
    container_name: judge-server
    restart: always
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/log:/log
      - ./data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://judge-server:8080
      - BACKEND_URL=http://oj-backend:8000/api/judge_server_heartbeat/
      - TOKEN=how_a_good_online_judge
  
  oj-backend:
    image: registry.cn-hangzhou.aliyuncs.com/onlinejudge/oj_backend
    container_name: oj-backend
    restart: always
    depends_on:
      - oj-redis
      - oj-postgres
      - judge-server
    volumes:
      - ./data/backend:/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
      - JUDGE_SERVER_TOKEN=CHANGE_THIS
    ports:
        - "0.0.0.0:10080:8000"
        - "0.0.0.0:10443:1443"

```

**Comment by LiuTianyouOnLuogu** [comment]
为什么访问不到，netstat没有绑定84端口的记录。
```
version: "2"
services:

  oj-redis:
    image: redis:4.0-alpine
    container_name: oj-redis
    restart: always
    volumes:
      - ./data/redis:/data
  
  oj-postgres:
    image: postgres:10-alpine
    container_name: oj-postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge

  judge-server:
    image: registry.cn-hangzhou.aliyuncs.com/onlinejudge/judge_server
    container_name: judge-server
    restart: always
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/log:/log
      - ./data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://judge-server:8080
      - BACKEND_URL=http://oj-backend:8000/api/judge_server_heartbeat/
      - TOKEN=how_a_good_online_judge
      # - judger_debug=1
  
  oj-backend:
    image: registry.cn-hangzhou.aliyuncs.com/onlinejudge/oj_backend
    container_name: oj-backend
    restart: always
    depends_on:
      - oj-redis
      - oj-postgres
      - judge-server
    volumes:
      - ./data/backend:/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
      - JUDGE_SERVER_TOKEN=CHANGE_THIS
      # - FORCE_HTTPS=1
      # - STATIC_CDN_HOST=cdn.oj.com
#    networks:
#        - oj-backend
    ports:
        - "0.0.0.0:10080:8000"
        - "0.0.0.0:10443:1443"
# networks:
#   oj-backend:
#       driver: bridge
#       ipv4_address: 127.100.10.11

```
