### ISSUE TITLE
backend 访问 judger 失败

### ISSUE THREAD

**Issue by Coda-s** [QingdaoU/OnlineJudge#493]
backend 访问 judger失败
查看 judger unicorn.log 日志发现 python 无法启动线程

目前解决方案是在 docker-compose.yml 中添加 seccomp
```
oj-judge:
    image: registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1
    security_opt:
      - seccomp=unconfined
```
